---
- name: Adicionar chave GPG da Mozilla
  ansible.builtin.shell: |
    curl -fsSL https://packages.mozilla.org/apt/repo-signing-key.gpg | gpg --dearmor -o /etc/apt/keyrings/mozilla.gpg
  args:
    creates: /etc/apt/keyrings/mozilla.gpg
  become: true

- name: Adicionar repositório apt da Mozilla
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/mozilla.gpg] https://packages.mozilla.org/apt mozilla main"
    state: present
    filename: mozilla
  become: true

- name: Configurar pin para preferir .deb da Mozilla
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/mozilla
    content: |
      Package: *
      Pin: origin packages.mozilla.org
      Pin-Priority: 1000
    mode: '0644'
  become: true

- name: Remover Firefox Snap
  ansible.builtin.command: snap remove firefox
  become: true
  when: remove_firefox_snap | bool
  failed_when: false
  changed_when: true

- name: Instalar Firefox
  ansible.builtin.apt:
    name: firefox
    state: present
    update_cache: true
  become: true
